### ISSUE TITLE
Disappeared from store? Violates Brave policy?

### ISSUE THREAD

**Issue by mysterybear** [ErikHumphrey/close-tabs-to-the-left#1]
Hey, I noticed this started having issues when I use it with Brave, it says it violates its policy

And now I can't find it in the store either.

Did something happen recently?

**Comment by ErikHumphrey** [comment]
Hi, thanks for reaching out. I have to submit an update to Google as the extension is requesting one more permission (`tabs`) than it actually needs to operate; expect this soon.

**Comment by ErikHumphrey** [comment]
An update has been submitted to Google to resolve this issue; it may temporarily affect the resolution of the extension icon, but that will be fixed when the next update is approved immediately after.

**Comment by ErikHumphrey** [comment]
All the fixes should be live now.
