### ISSUE TITLE
Doesn't work after Chrome update

### ISSUE THREAD

**Issue by Mystic-Mirage** [ErikHumphrey/close-tabs-to-the-left#2]
Hey!

The extension stopped working after the Chrome update

Browser: Chrome Version 91.0.4472.77 (Official Build) (64-bit)
OS: Xubuntu 20.04 (64-bit)

**Comment by ErikHumphrey** [comment]
Thanks for mentioning your OS. I can't reproduce this bug on Windows or macOS using Chrome v91.0.4472.77 or Chrome v91.0.4472.106, so I'll try on Xubuntu 20.04 eventually if you're still experiencing this issue. The code is quite simple, though, so it's weird there's a platform-specfic issue.

**Comment by Mystic-Mirage** [comment]
I have two profiles in my Google Chrome (personal and work) and both have the extension installed.
Today it started to work but only for one profile. Version is the same -- 1.2.1. Quite strange...

**Comment by Mystic-Mirage** [comment]
Found the difference. In my personal profile, I've got "allow in incognito mode" enabled for the extension. Enabled it in my work profile and it started to work.

But the most interesting thing it continues to work even after I've switched off this setting. So for me to get the extension to work I needed to switch on/off the incognito permission...

**Comment by Mystic-Mirage** [comment]
It stopped working again today for one account. Another account wasn't affected.
Disabling and then enabling the extension fixed the problem.

**Comment by ErikHumphrey** [comment]
That's really strange. This doesn't seem like something I can fix, but as I haven't explored any options yet I'll hold off on closing this for now.

**Comment by Mystic-Mirage** [comment]
Hasn't happened to me for more than a year, so closing the issue
